# Generated by Django 4.2.6 on 2025-06-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ingredients_product_safety_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
